### PR TITLE
Add instructions to create and use a virtual environment

### PR DESCRIPTION
**Pull request by kirang89**
It is vital for beginners to use a virtual environment for all their development work. This commit adds instructions for creating and activating a virtual environment using `virtualenv` for development.

### CODE REVIEW

**Comment by shrayasr** [comment]
> It is vital for beginners to use a virtual environment for all their development work. 

+1

> We do not have dependencies, do you still think we need a virtualenv?

Its in good practice. If you DO need a dependency, already having a virtualenv facilitates it.

**Comment by bravegnu** [comment]
The problem is virtualenv is not the silver bullet to dependency management, which everybody is made to believe. It works for web developers, but for GUI developers and people doing scientific computing, it doesn't help much. Read https://pythonrants.wordpress.com/2013/12/06/why-i-hate-virtualenv-and-pip/ and https://hynek.me/articles/virtualenv-lives/

So for true portable isolation you will require virtual box / docker + virtualenv + pipsi. And this combo will introduce a host of other problems!

But one reason to use virtualenv here, is to make sure you do not have to have root access to run `python setup.py develop`. Will check if there is a better way to do it.

**Comment by kirang89** [comment]
@bravegnu Thanks for sharing the articles!

While I do believe the best method for isolation is a combo of docker and virtualenv, the latter has worked for me for all sorts of simple projects. 

If there aren't going to be any dependencies at all, please ignore this PR. It's just that I don't like installing packages directly onto my system for development/experimentation.

**Comment by bravegnu** [comment]
OK. Merging it, the dependencies that this project generates can be contained by virtualenv.

**Pull request merged**
